import "@/styles/main.scss";

import { Manrope } from "next/font/google";

const manrope = Manrope({
  display: "swap",
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font",
  weight: ["800"],
});

export const metadata = {
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.png",
      type: "image/png",
    },
    shortcut: { url: "/favicon.png", type: "image/png" },
  },
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={manrope.variable} lang="en">
      <body>{children}</body>
    </html>
  );
}
